import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { WishlistProvider } from "./(pages)/(public)/wishlist/ContextWishlist/WishlistContext";
import SessionWrapper from "./api/auth/SessionWrapper";
import { ToastContainer } from "react-toastify";
// import StripeWrapper from "./(pages)/(public)/checkout/stripe_provider/Stripe_Wrapper"; // Import StripeWrapper
import { CartProvider } from "./(pages)/(public)/cart/context/CartContext";
import Footer from "./components/HomeComponent/footer";
import Header from "./components/HomeComponent/header";
import TopHeader from "./components/HomeComponent/TopHeader";
// import CartProviderStripe from "./(pages)/(public)/components/CartProviderStripe";
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "E-Commerce Website",
  description: "Generated by create Mubashir Saeedi",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <SessionWrapper>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          {/* <CartProviderStripe> */}
          <CartProvider>  
            <WishlistProvider>
              <TopHeader />
              <Header />
              {children}
              <ToastContainer />
            </WishlistProvider>
          </CartProvider>
          {/* </CartProviderStripe> */}
          {/* <StripeWrapper /> */}
          <Footer />
        </body>
      </SessionWrapper>
    </html>
  );
}
